[prune]
  non-go = true
  go-tests = true
  unused-packages = true

#[[constraint]]
#  name = "github.com/mattermost/mattermost-server"
#  version = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.3.0"
